name: Update Data
on:
  schedule:
    # - cron: '0 4/12 * * *'
    # TEST
    - cron: '0 5/12 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # setup node.js environment
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      # checkout program branch
      # pwd is now @/repo
      - uses: actions/checkout@v1
        with:
          ref: program
          fetch_depth: 1
          path: repo
      # copy program to outside since checkout will reset workspace
      - run: |
          cp -R . ../program
      # checkout storage branch
      # pwd is now @/storage
      - uses: actions/checkout@v1
        with:
          ref: master
          fetch_depth: 1
          path: storage
      # run the program
      - run: |
          cd ../program
          yarn
          node .
      # create git commit and push
      - run: |
          git config user.name 'kpcc-updater'
          git config user.email ''
          git add .
          git commit -m $(cat ../BATCH_NO) || echo No updates
          git remote set-url origin https://SilentDepth:$GITHUB_TOKEN@github.com/SilentDepth/kpcc-stats-data.git
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
