name: Update Data
on:
  schedule:
    - cron: '0 10/12 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Run crawler
      run: |
        cd ./crawler
        yarn
        node .
    - name: Create git commit and push
      run: |
        git config user.name 'kpcc-updater'
        git config user.email ''
        git add .
        git commit -m $(cat BATCH_NO) || echo No updates
        git remote set-url origin https://SilentDepth:$GITHUB_TOKEN@github.com/SilentDepth/kpcc-stats-data.git
        git push origin HEAD:master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
